"""empty message

Revision ID: 3111b8566a50
Revises: ab68ba1dee02
Create Date: 2022-01-02 02:32:11.214449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3111b8566a50'
down_revision = 'ab68ba1dee02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'company', ['company_name_ko'])
    op.create_unique_constraint(None, 'company', ['company_name_en'])
    op.create_unique_constraint(None, 'company', ['company_name_ja'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='unique')
    op.drop_constraint(None, 'company', type_='unique')
    op.drop_constraint(None, 'company', type_='unique')
    # ### end Alembic commands ###
