"""empty message

Revision ID: ab68ba1dee02
Revises: 
Create Date: 2022-01-01 20:34:51.996837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab68ba1dee02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name_ko', sa.String(length=50), nullable=True),
    sa.Column('company_name_en', sa.String(length=50), nullable=True),
    sa.Column('company_name_ja', sa.String(length=50), nullable=True),
    sa.Column('tag_ko', sa.String(length=50), nullable=True),
    sa.Column('tag_en', sa.String(length=50), nullable=True),
    sa.Column('tag_ja', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company')
    # ### end Alembic commands ###
